version: "3.9"
services:
  database:
    image: postgres:13
    env_file: ./database/.env
    container_name: local-db
    ports:
      - 5432:5432

  database-config:
    build: ./database-config
    env_file: ./database-config/.env
    volumes:
      - ./docker-utils:/docker-utils
      - ./database-config/.pgpass:/root/.pgpass
      - ./database-config:/database-config/

  aws-connection:
    image: jnovack/autossh
    environment:
      - SSH_TARGET_HOST=169.254.169.254
      - SSH_TARGET_PORT=80
      - SSH_TUNNEL_PORT=9002
      - SSH_REMOTE_USER=ubuntu
      - SSH_REMOTE_HOST=13.232.215.119
      - SSH_MODE=-L
      - SSH_BIND_IP=0.0.0.0
    volumes:
      - ~/.ssh/id_rsa:/id_rsa 
    ports:
      - 9002:9002
    container_name: aws-connection